/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    ACarousel: typeof import('ant-design-vue/es')['Carousel']
    AConfigProvider: typeof import('ant-design-vue/es')['ConfigProvider']
    ADivider: typeof import('ant-design-vue/es')['Divider']
    AEmpty: typeof import('ant-design-vue/es')['Empty']
    AInput: typeof import('ant-design-vue/es')['Input']
    ARadioButton: typeof import('ant-design-vue/es')['RadioButton']
    ARadioGroup: typeof import('ant-design-vue/es')['RadioGroup']
    ASteps: typeof import('ant-design-vue/es')['Steps']
    CategoryButton: typeof import('./src/components/home/CategoryButton.vue')['default']
    CommentComponent: typeof import('./src/components/comment/CommentComponent.vue')['default']
    GuideImageGallery: typeof import('./src/components/guide/GuideImageGallery.vue')['default']
    HeartIcon: typeof import('./src/components/guide/HeartIcon.vue')['default']
    ImageGallery: typeof import('./src/components/resort/ImageGallery.vue')['default']
    PageHeader: typeof import('./src/components/page/PageHeader.vue')['default']
    RecommendScenicSpot: typeof import('./src/components/home/RecommendScenicSpot.vue')['default']
    RecommendTravelGuide: typeof import('./src/components/resort/RecommendTravelGuide.vue')['default']
    RecommendTravelNote: typeof import('./src/components/home/RecommendTravelNote.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SmallMap: typeof import('./src/components/resort/SmallMap.vue')['default']
    SvgIcon: typeof import('./src/components/svgIcon/index.vue')['default']
    WriteComment: typeof import('./src/components/comment/WriteComment.vue')['default']
  }
}
